### ISSUE TITLE
fatal: 'no_push' does not appear to be a git repository

### ISSUE THREAD

**Issue by fnune** [CKolkey/neogit#38]
### Description

When running `pp` to pull from origin I get this:

```
git --no-pager -c color.ui=always --no-optional-locks pull no_push master --rebase:
    fatal: 'no_push' does not appear to be a git repository
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

    Open the console for details
```

This is what I see in the popup:

![image](https://github.com/CKolkey/neogit/assets/16181067/374a2947-ee7d-4ffc-82cd-f4a06545a652)

Not sure if this is a misconfiguration of my repo?

### Neovim version

0.9.1

### Operating system and version

Debian 12 (bookworm)

### Steps to reproduce

-

### Actual behavior

-

### Minimal config

```Lua
-
```

**Comment by CKolkey** [comment]
So, this isn't a bug. `pp` doesn't pull from origin - it pulls from the current `pushRemote` for the branch. Thats _often_ `origin`, but it's set via the config value `branch.<branch name>.pushRemote`. In your screenshot, it says "pull into master from: no_push/master`. So your branch's pushRemote is `no_push`. No idea why 🤷🏼 

Fortunately, it's very easy to change :)

You can check what it's currently set to in the branch popup, or the branch config popup (`pC`):
<img width="445" alt="Screenshot 2023-06-12 at 23 28 37" src="https://github.com/CKolkey/neogit/assets/7228095/01d351db-8343-49c5-9658-d66bf1750c9c">

To pull from origin, use `pu`. In fact, for many different popups, the `p` action will use the pushRemote, and the `u` action will use origin.

I'm going to close this, since it seems like it's working exactly as expected, but feel free to reopen if you disagree, or think it could be handled differently.

**Comment by fnune** [comment]
Ah interesting. Sorry about that!

And thanks for the tip. I'll figure this out.

**Comment by CKolkey** [comment]
No worries - the only reason I know any of this is from engineering the magit source to figure out how to implement it here.
